---
title: "Entering and cleaning data #3"
output: 
  beamer_presentation:
    theme: "Frankfurt"
    colortheme: "seagull"
    fonttheme: "structuresmallcapsserif"
fontsize: 10pt
---

```{r setup, include=FALSE}
library(knitr)
```

# Pulling online data

## APIs

# Example R API wrappers

## rOpenSci

rOpenSci (https://ropensci.org): 

> "At rOpenSci we are creating packages that allow access to data repositories through the R statistical programming environment that is already a familiar part of the workflow of many scientists. Our tools not only facilitate drawing data into an environment where it can readily be manipulated, but also one in which those analyses and methods can be easily shared, replicated, and extended by other researchers."

## rOpenSci

rOpenSci collects a number of packages for tapping into open data for research: https://ropensci.org/packages

Some examples (all descriptions from rOpenSci): 

- `AntWeb`: Access data from the world's largest ant database. 
- `chromer`: Interact with the chromosome counts database (CCDB)
- `gutenbergr`: Download and process public domain works in the Project Gutenberg collection
- `musemeta`: R Client for Scraping Museum Metadata, including The Metropolitan Museum of Art, the Canadian Science & Technology Museum Corporation, the National Gallery of Art, and the Getty Museum, and more to come.
- `rnoaa`: Access climate data from NOAA, including temperature and precipitation, as well as sea ice cover data, and extreme weather events
- `rusda`: Interface to some USDA databases
- `stplanr`: Functionality and data access tools for transport planning, including origin-destination analysis, route allocation and modelling travel patterns
- `webchem`: Retrieve chemical information from many sources. Currently includes: Chemical Identifier Resolver, ChemSpider, PubChem, and Chemical Translation Service.

## USGS

# Parsing webpages

## `rvest`