# (APPENDIX) Appendices {-}

# Appendix A: Vocabulary

You will be responsible for knowing the following functions and vocabulary for the weekly quizzes.

## Week 1 (Quiz 1)

- `c()`
- `data.frame()`
- `dim()`
- `ncol()`
- `nrow()`
- `head()`, option `n = `
- `read.csv`, options `head = `, `skip = `, `nrow = `
- `[...]`, `[..., ...]`
- `getwd()`
- `setwd()`, including `setwd("~")`
- `list.files()`
- `install.packages()`
- `library()`
- `<-`
- `=`
- `subset()`
- `length()`
- open source software
- "free as in beer"
- "free as in speech"
- CRAN
- GitHub
- R packages
- R working directory
- How to download a csv file from GitHub
- Nate Silver
- FiveThirtyEight
- Grading policies for the course
- Course requirements / policies for in-class quizzes and weekly journal entries
- Style rules for naming R objects
- Difference between R and RStudio
- Vectors
- Dataframes
- Note: Pay attention in the course notes and exercise to where the code uses quotation marks and where it does not-- this will help you in the quiz

## Week 2 (Quiz 2)

- `source()`
- `setwd()`, including `setwd("~")`, `setwd("..")`, `setwd("..\..")`
- `list.files()`, option `path =`
- functions in the `read.table()` family, including `read.csv()` and `read.delim()`. What are defaults of the `sep = ` and `dec = ` options for each? For all, the options `header = `, `sep = `, `as.is = `, `na.strings = `, `nrows = `, `skip = `, and `col.names = `.
- The tidyverse
- functions in the `read_*` family (e.g., `read_csv`)
- Advantages of the `read_*` family of functions compared to their base R analogues (the `read.table` functions)
- `paste()`, option `sep = `
- `paste0()`
- `readxl` package and its `read_excel()` function
- `haven` package and its `read_sas()` function
- `$`
- `class()`
- `str()`
- `as.Date()`, option `format = `
- `lubridate` functions, include `ymd`, `ymd_hm`, and `mdy`
- `range()` 
- `dplyr` package
- `rename()`
- `mutate()`
- `arrange()`
- `%>%`, advantages of piping
- `filter()`
- Reading in data from either a local or online flat file
- `save()`, option `file = `
- `load()`
- `rm()`
- `ls()`
- Main types of vector classes in R: character, numeric, factor, date, logical
- Which classes of vectors don't always look like numbers, but R assigns an underlying numeric value to? (Hint: This include the logical class, which R saves with an underlying number, with TRUE = 1 and FALSE = 0.)
- Common abbreviations for telling R date formats (e.g., "%m", "%y")
- Common logical expressions to use in `filter()`
- relative pathnames
- absolute pathnames
- delimited files
- fixed width files
- R script file (How would you make a new one? What file extension would it have? Why is it important to use? How do you run code from a script file in RStudio?)
- What kinds of data can be read into R?
- How to read flat files of data that are online directly into R if they are on:
    + A "http:" site
    + A "https:" site
- When you might want to save an R object as a `.RData` file and when (and why) you might not want to

## Week 3 (Quiz 3)

- `data()` (with and without the name of a dataset as an option)
- `library()` (with and without an argument in the parentheses)
- common addition for all these plotting functions: `ggtitle`, `xlab`, `ylab`, `xlim`, `ylim`
- `aes` function and common aesthetics, including `color`, `shape`, `x`, `y`, and `fill`
- Some common geoms: `geom_histogram`, `geom_points`, `geom_lines`, `geom_boxplot()` (both for a single numeric variable and for a numeric vector stratified by a factor)
- `ggpairs()` from the `GGally` package
- `range()`
- `min()`
- `max()`
- `mean()`
- `median()`
- `table()`
- `cor()`, both for two variables in a dataframe, and to get the correlation matrix for several variables in a dataframe
- `summary()`, as applied to: different classes of vectors (numeric, factor, logical), dataframes, `lm` objects, and `glm` objects
- `lm()`, `data=` option
- `glm()`, options `data=`, `family=`
- Functions to apply to a `lm` or `glm` object: `summary()`, `coef()`, `residuals()`, `fitted()`, `plot()`, `abline()`
- The following elements that you can pull from the `summary` of a `lm` call: `summary(mod_1)$call`, `summary(mod_1)$coef`, `summary(mod_1)$r.squared`, `summary(mod_1)$cov.unscaled`
- How to create a logical vector and how to use one to (1) index a data frame and (2) count the number of times a certain condition is true in a vector
- What the bang operator (`!`) does to a logical operator
- What to do if you want to apply a summary statistic function to a vector with missing values (you do not need to know every option name for all the functions, just know that you would need to include an option like `na.rm=` or `use=`, and that you can use the help file for a function to figure out the option call for that function).
- The following about object-oriented programming: In R, it means that some functions, like `summary()`, will do different things depending on what type of object you call it on.
- The basic structure of regression formulae in R (for example, `y ~ x1 + x2`)
- Difference between using `lm()` and `glm()` to fit a linear regression model
- Difference between the code you would use to fit a linear, Poisson, or logistic model using `glm()`

## Week 4 (Quiz 4)

- Guidelines for good graphics
- Data density / data-to-ink ratio
- Small multiples
- Edward Tufte
- Hadley Wickham
- Where to put the `+` in ggplot statements to avoid problems (ends of lines instead of starts of new lines)
- Can you save a ggplot object as an R object that you can reference later? If so, how would you add elements on to that object? How would you print it when you were ready to print the graph to your RStudio graphics window?
- `geom_hline()`, `geom_vline()`
- `geom_text()`
- `facet_grid()`, `facet_wrap()`
- `grid.arrange()` from the `gridExtra` package
- `ggthemes` package, including `theme_few()` and `theme_tufte()`
- Setting point color for `geom_point()` both as a constant (all points red) and as a way to show the level of a factor for each observation
- `size`, `alpha`, `color`
- Re-naming and re-ordering factors
- **Note:** If you read this and find and bring in an example of a "small multiples" graph (from a newspaper, a website, an academic paper), you can get one extra point on this quiz

## Week 5 (Quiz 5)

- Reproducible research, including what it is and advantages to aiming to make your research reproducible
- R style guidelines on variable names, `<-` vs. `=`, line length, spacing, semicolons, commenting, indentation, and code grouping
- Markup languages (concept and examples)
- Basic conventions for Markdown (bold, italics, links, headers, lists)
- Literate programming
- What working directory R uses for code in an .Rmd document
- Basic syntax for RMarkdown chunks, including how to name them
- Options for RMarkdown chunks: `echo`, `eval`, `messages`, `warnings`, `include`, `fig.width`, `fig.height`, `results`
- Difference between global options and chunk options, and which takes precendence
- What inline code is and how to write it in RMarkdown
- How to set global options
- Why style is important in coding
- RPubs

## Week 6 (Quiz 6)

- `with()`
- Three characteristics of tidy data
- Five common problems with tidy data and how to resolve them (make sure you understand the examples shown, which you can find out more about in the Hadley Wickham paper I reference)
- `select()`
- `filter()`
- `mutate()`
- `summarize()`
- `group_by()`
- `arrange()`
- `gather()`
- `spread()`
- `%>%`
- Go through the examples where I've chained together several functions to clean up a dataset and make sure you can follow through these chained examples

## Week 7 (Quiz 7)
- `for` loops
- basics of writing a function
- figuring out the output of a loop based on its code
- figuring the the output of a function based on its code
- parentheses around a full assignment statement (e.g., `(ex <- 1)`)
- in-class exercise and example analysis from Oct. 12 course
- `kable()` from the `knitr` package

## Week 8 (Quiz 8)
- `apply` family of functions
- `*_join` family of functions
- `matrix` objects, including how to subset
- `list` objects, including how to subset
- `Titanic` example analysis from Oct. 19 course
- Using `color =`, `size =`, or `shape =` in the `aes()` statement of a `ggplot()` call
- `geom_bar()`
- `geom_smooth()`, including the `se =` and `method =` options
- jittering, the `position = position_jitter()` option in ggplot geoms