---
title: "Course overview"
output: 
  beamer_presentation:
    theme: "metropolis"
fontsize: 10pt
---

## Time, place, and TA

- Time: Mondays and Wednesdays, 10:00 am--12:00 pm
- Exceptions: 
    + There will be no meeting on Labor Day (Monday, Sept. 3).
    + There are no course meetings the week of Thanksgiving (week of Nov. 19).
    + I will be away from Fort Collins for two course dates (Aug. 27 and 29). For that week, I will post video lectures online for you to watch that week. That Friday (Aug. 31), I will hold a session from 10--11 am for anyone who would like to do the in-course exercises under supervision (for which attendance would not be counted towards the course attendance grade).
- Place: Environmental Health Building, Room 120
- Additional Faculty: Dr. Nicholas Good
- Office hours: Fridays, 10:00 am--11:00 am

## Course book

- There is an online book for this course available at:  [https://geanders.github.io/RProgrammingForResearch/](https://geanders.github.io/RProgrammingForResearch/)
- This book includes course information, course notes, links to download pdfs of lecture slides, in-course exercises, homework assignments, and vocabulary lists for quizzes. 
- This online book is still in development, so it will be evolving throughout the semester. The second half of the book, in particular, is still in a pretty raw form. 
- The book can be downloaded as a pdf or an eBook. 
- Otherwise, we do not have a required textbook for this class. I have, however, listed some additional resources I recommend, particularly *R for Data Science* by Garrett Grolemund and Hadley Wickham.

## Laptops

- Please plan to bring a personal laptop to all classes. 
- If you do not have access to a laptop you can bring to class, talk to me and we can try to figure something out.

## Content

We will cover four large themes in this course:

- Entering and cleaning data
- Exploring data
- Reporting data results
- Reproducible research

## Content

The first course is preliminaries, and after that there will be three "cycles" of covering these topics:

- **Preliminaries** Week 1
- **Basic** Weeks 2--5
- **Intermediate** Weeks 6--9
- **Advanced** Weeks 10--15
- **Final** Week 16

A detailed course schedule is available in the online course book.

## Grading

Your grade will be determined based on the following components:

```{r echo = FALSE}
a <- data.frame(a = c("Final group project",
                      "Weekly in-class quizzes, weeks 3--10",
                      "Homework",
                      "Attendance and class participation",
                      "Weekly in-course group exercises"),
                b = c(30, 25, 25, 10, 10))
knitr::kable(a, col.names = c("Assessment component", 
                              "Percent of grade"))
```

## Attendance and class participation

Because so much of the learning for this class is through interactive work in class, it is critical that you come to class. 

\medskip

Out of a possible 10 points for class attendance, you will get:

- **10 points** if you attend all classes
- **8 points** if you miss one class
- **6 points** if you miss two classes
- **4 points** if you miss three classes
- **2 points** if you miss four classes
- **0 points** if you miss five or more classes

## Attendance and class participation

Excused absences: 

- CSU-related: This is typically missing to attend a conference or for a field study for your research. To be excused, this requires a letter from your advisor.
- Serious medical issue: To be excused, this requires a letter from a doctor or other medical professional. 

## Weekly in-course group exercises

- Ten points of your final grade will be based on your participation in in-course group exercises. 
- As long as you are in class and participate in these exercises, you will get full credit for this component. 
- If you miss a class, to get credit towards this component of your grade, you will need to turn in a one-page document describing what you learned from doing the in-course exercise on your own time. You must submit this to me within a week of your absence to get this credit.
- All in-class exercises are included in the online course book at the end of the chapter on the associated material.

## Homework

- There will be six homework assignments, starting a few weeks into the course and then due approximately every two weeks (see detailed schedule in the online course book).
- The first homeworks should be done individually. For later homeworks, you will often have the choice to work together in groups.
- Homeworks will be graded for correctness, but some partial credit will be given for questions you try but fail to answer correctly. 
- For later homeworks with detailed coding, we will randomly select a subset of the questions to grade in detail, providing extensive feedback on the code. The other questions will be graded for completeness and correctness. We will provide solution code for all questions.
- Homework is due by the start of class on the due date. Your grade will be reduced by 10 points for each day it is late, and will receive no credit if it is late by over a week. 

## Final group project

The final group project will be graded with A through F, with the following point values (out of 30 possible):

- **30 points** for an A
- **25 points** for a B
- **20 points** for a C
- **15 points** for a D
- **10 points** for an F

If you turn nothing in, you will get **0 points**.

## Final group project

- You will do the final group project in groups of 2--3. 
- All groups will be working on a larger R programming project. Each group will be responsible for specific elements of the overall project. 
- Final products will include R code for the group's portion of the project, a final oral presentation from each group presenting their final product, and a short written report from each group giving examples of applying the tools they developed.
- You will have in-class group work time during weeks 10--15 to work on this. This project will also require some work with your group outside of class. 
- You will be able to get feedback from me through GitHub in these weeks. I will also provide feedback and help during the in-class group work time. 
- We will discuss expectations and grading for this, create groups, etc. around the middle of the semester.

<!-- ## Final group project -->

<!-- - You will do the final group project in groups of 2--3.  -->
<!-- - The final product will be a statistical blog post-style article of 1,500 words or less and an accompanying Shiny web application. Come up with an interesting question you'd love to get the answer to that you think you can find data to help you answer.  -->
<!-- - You will need to use the data you find, and R, to write your article.  -->
<!-- - The final product will be a Word document created from an RMarkdown file and an accompanying Shiny web application.  -->

<!-- ## Final group project -->

<!-- - You will have in-class group work time during weeks 10--15 to work on this. This project will also require some work with your group outside of class.  -->
<!-- - You will be able to get feedback from me through weekly informal written reports in these weeks. I will also provide feedback and help during the in-class group work time.  -->

<!-- ## Final group project -->

<!-- To get an idea of what your final product should look like, check out these links: -->

<!-- - [Does Christmas come earlier each year?](http://www.statslife.org.uk/culture/1892-does-christmas-really-come-earlier-every-year) -->
<!-- - [Hilary: the most poisoned baby name in US history](http://hilaryparker.com/2013/01/30/hilary-the-most-poisoned-baby-name-in-us-history/) -->
<!-- - [Every Guest Jon Stewart Ever Had On "The Daily Show"](http://fivethirtyeight.com/datalab/every-guest-jon-stewart-ever-had-on-the-daily-show/) -->
<!-- - [Should Travelers Avoid Flying Airlines That Have Had Crashes in the Past?](http://fivethirtyeight.com/features/should-travelers-avoid-flying-airlines-that-have-had-crashes-in-the-past/) -->
<!-- - [Billion-Dollar Billy Beane](http://fivethirtyeight.com/features/billion-dollar-billy-beane/) -->

<!-- ## Final group project -->

<!-- - We will discuss expectations and grading for this, create groups, etc. around the middle of the semester.  -->
<!-- - The focus for this will be on finding, cleaning, and using good data to answer an interesting question, and on presenting, summarizing, and explaining the data well. -->



## In-class quizzes

- You will have eight total in-class quizzes. You will have one for each of the Week 3--10 class meetings. 
- There will be *at least* 10 questions per quiz. You will get 1/3 point for each correct answer. 
- If you do the math, you can get full credit for this even if you don't get all of your answers right...
- You can not get more than the maximum of 25 points for this component.

## In-class quizzes

- All quizzes will be multiple choice, matching, or some other form of "close-answered" question (i.e., no open-response-style questions).
- If you miss a quiz, the only available make-up time will be during office hours (10--11 am on the Friday of the quiz you missed). If you miss a quiz and are unable to do the make-up during this time, you can still get full credit on your total possible quiz points if you miss a class, but it means you will have to work harder and get more questions right for days you are in class.
- I **will not** ever re-consider the score you got on a previous quiz, give points back for a wrong answer on a poorly-worded question, etc. However, if a lot of people got a particular question wrong, I will be sure to cover it in the next class period. Also, especially if a question was poorly worded and caused confusion, I will work a similar question into a future quiz.

## In-class quizzes

- The "Vocabulary" appendix of our online book has the list of material for which you will be responsible for this quiz. 
- Most of the functions and concepts will have been covered in class, but some may not. 
- You are responsible for going through the list and, if there are things you don't know or remember from class, learning them. To do this, you can use help functions in R, Google, StackOverflow, books on R, ask a friend, and any other resource you can find.
- Using R frequently in your research or other coursework will also help you prepare. 
- This list will be finalized by the Wednesday night before each quiz.

## In-class quizzes

An example of the vocabulary list:

- `c()`
- R object
- `dim()`
- `head()`, parameter `n = `
- open source software
- Nate Silver

## What you have due soon

- Wednesday, Sept. 5, during class: First in-class quiz. The "Vocabulary" appendix of our online book has the list of material for which you will be responsible for this quiz (Quiz 1 list). 

